реализация stats
deicida6/java-explore-with-me pull request #1
Opened 2024-08-20 12:01 UTC by deicida6

2024-08-22 05:52 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-08-22 05:52 UTC, ErkinKasymaliev commented on stats/stats-dto/src/main/java/ru/practicum/ewm/dto/stats/ViewStats.java
> +@NoArgsConstructor
@NoArgsConstructor и @AllArgsConstructor не нужны здесь, @Data уже содержит эти аннотации

2024-08-22 05:52 UTC, ErkinKasymaliev commented on stats/stats-server/src/main/java/ru/practicum/ewm/server/stats/model/EndpointHit.java
> +@NoArgsConstructor
@NoArgsConstructor и @AllArgsConstructor не нужны здесь, @DaTa уже содержит эти аннотации

2024-08-22 05:52 UTC, ErkinKasymaliev commented on stats/stats-server/src/main/java/ru/practicum/ewm/server/stats/controller/StatsServerController.java
> +    public List<ViewStats> getStats(@RequestParam(name = "start") String start,
@RequestParam(name = "start") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDateTime start,
@RequestParam(name = "end") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDateTime end
дальше парсить в сервисе дату не надо

2024-08-22 06:45 UTC, deicida6 commented on stats/stats-server/src/main/java/ru/practicum/ewm/server/stats/controller/StatsServerController.java
> +    public List<ViewStats> getStats(@RequestParam(name = "start") String start,
но там же на входе String получаем, дальше он начинает ругаться что ему не удается резолвить String в LocalDateTime, если я вставлю код из сервиса в контроллер где парсится строка, это будет корректно?

2024-08-22 06:48 UTC, ErkinKasymaliev commented on stats/stats-server/src/main/java/ru/practicum/ewm/server/stats/controller/StatsServerController.java
> +    public List<ViewStats> getStats(@RequestParam(name = "start") String start,
Ну поменяйте в сервис string на localdatetime

2024-08-22 06:56 UTC, deicida6 commented on stats/stats-server/src/main/java/ru/practicum/ewm/server/stats/controller/StatsServerController.java
> +    public List<ViewStats> getStats(@RequestParam(name = "start") String start,
исправлено

2024-08-22 06:56 UTC, deicida6 commented on stats/stats-server/src/main/java/ru/practicum/ewm/server/stats/model/EndpointHit.java
> +@NoArgsConstructor
исправлено

2024-08-22 06:56 UTC, deicida6 commented on stats/stats-dto/src/main/java/ru/practicum/ewm/dto/stats/ViewStats.java
> +@NoArgsConstructor
исправлено

2024-08-23 05:04 UTC, ErkinKasymaliev requested changes
почему не исправили коммент в StatsServerController?

2024-08-23 05:04 UTC, ErkinKasymaliev commented on stats/stats-server/src/main/java/ru/practicum/ewm/server/stats/controller/StatsServerController.java
> +            @RequestParam(name = "start") String startString,
а почему здесь не исправили?

2024-08-23 06:04 UTC, deicida6 commented on stats/stats-server/src/main/java/ru/practicum/ewm/server/stats/controller/StatsServerController.java
> +            @RequestParam(name = "start") String startString,
исправил же, перенес парсинг строк в контроллер, версию @RequestParam(name = "start") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDateTime start,
@RequestParam(name = "end") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDateTime end которые вы написали не работают
там ниже в методе сам парсинг

2024-08-23 07:14 UTC, deicida6 commented on stats/stats-server/src/main/java/ru/practicum/ewm/server/stats/controller/StatsServerController.java
> +            @RequestParam(name = "start") String startString,
исправлено

2024-08-23 09:28 UTC, ErkinKasymaliev approved these changes
работа принята

2024-08-23 16:32 UTC, merged