реализация основного сервиса
deicida6/java-explore-with-me pull request #2
Opened 2024-08-28 07:51 UTC by deicida6

2024-09-01 12:45 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-09-01 12:45 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private boolean pinned;
isPinned

2024-09-01 12:45 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/controllers/priv/ParticipationPrivateController.java
> +public class ParticipationPrivateController {
UserPrivateController. 
ParticipationPrivateController вводит в заблуждение, так как path контроллера /users

2024-09-01 12:45 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventFullDto.java
> +    private Boolean paid;
isPaid

2024-09-01 12:45 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventFullDto.java
> +    private Boolean requestModeration;
isRequestModeration, для boolean желательно добавлять is

2024-09-01 12:45 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +                .createdOn(event.getCreatedOn().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")))
DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss") -- это в константу

2024-09-01 12:45 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +    private String error(Exception e) throws IOException {
в конец класса

2024-09-01 12:45 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +    public @NotNull
формативание поплыло, нет аннотации и почему ResponseEntity<Object>?

2024-09-01 12:45 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +    public ResponseEntity<ApiError> handleConstraintViolation(ConstraintViolationException ex) {
здесь вы обернули в ResponseEntity, а ниже просто ApiError. Используйте один стиль

2024-09-01 12:45 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/controllers/priv/ParticipationPrivateController.java
> +    private final ParticipationService participationService;
тут также UserService

2024-09-01 12:45 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/controllers/priv/ParticipationPrivateController.java
> +    private final ParticipationService participationService;
ну UserRepository

2024-09-01 13:41 UTC, deicida6 commented on main-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private boolean pinned;
![image](https://github.com/user-attachments/assets/6d7533f0-f762-47f5-8490-10b1865baf90)
а то что в спецификации данной к диплому используется pinned получается тоже не правильно?

2024-09-01 13:43 UTC, deicida6 commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventFullDto.java
> +    private Boolean paid;
![image](https://github.com/user-attachments/assets/ec20a53e-c620-4778-8138-0d0792b427a6)
аналогично, получается в спецификации не правильно?

2024-09-01 13:45 UTC, deicida6 commented on main-service/src/main/java/ru/practicum/ewm/controllers/priv/ParticipationPrivateController.java
> +public class ParticipationPrivateController {
исправил

2024-09-01 13:45 UTC, deicida6 commented on main-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private boolean pinned;
исправил

2024-09-01 13:45 UTC, deicida6 commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventFullDto.java
> +    private Boolean requestModeration;
исправил

2024-09-01 13:53 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private boolean pinned;
Хорошо, видимо у меня различаются мнения на этот счет с автором этого задания) оставляйте как есть

2024-09-01 13:58 UTC, deicida6 commented on main-service/src/main/java/ru/practicum/ewm/event/mapper/EventMapper.java
> +                .createdOn(event.getCreatedOn().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")))
исправлено

2024-09-01 13:58 UTC, deicida6 commented on main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +    private String error(Exception e) throws IOException {
исправил

2024-09-01 14:05 UTC, deicida6 commented on main-service/src/main/java/ru/practicum/ewm/controllers/priv/ParticipationPrivateController.java
> +    private final ParticipationService participationService;
participationService это же некая прослойка между юзером и контроллером, сам сервис то думаю правильно по логике, UserService уже в participationService находится, все равно добавить?

2024-09-01 14:11 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/ewm/controllers/priv/ParticipationPrivateController.java
> +    private final ParticipationService participationService;
Думаю вы правы, оставляйте

2024-09-01 14:21 UTC, deicida6 commented on main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +    public ResponseEntity<ApiError> handleConstraintViolation(ConstraintViolationException ex) {
исправил

2024-09-01 14:27 UTC, deicida6 commented on main-service/src/main/java/ru/practicum/ewm/controllers/priv/ParticipationPrivateController.java
> +    private final ParticipationService participationService;
отправил на повторную проверку, посмотрите пожалуйста как будет время.

2024-09-02 05:06 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2024-09-02 06:46 UTC, merged